# Generated by Django 3.2.9 on 2021-11-19 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challenge_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.CharField(blank=True, max_length=100)),
                ('contents', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Challenge',
                'ordering': ('challenge_id', 'name', 'start_date', 'end_date', 'image', 'contents', 'creator_id'),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'User',
                'ordering': ('user_id',),
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('target_id', models.ForeignKey(db_column='target_id', on_delete=django.db.models.deletion.CASCADE, related_name='Opponent', to='hackapp.user')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='OneSelf', to='hackapp.user')),
            ],
            options={
                'db_table': 'Follow',
                'ordering': ('num', 'user_id', 'target_id'),
            },
        ),
        migrations.CreateModel(
            name='Challenge_User',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('challenge_id', models.ForeignKey(db_column='challenge_id', on_delete=django.db.models.deletion.CASCADE, to='hackapp.challenge')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='hackapp.user')),
            ],
            options={
                'db_table': 'Challenge_User',
                'ordering': ('challenge_id', 'user_id', 'num'),
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='creator_id',
            field=models.ForeignKey(db_column='creator_id', on_delete=django.db.models.deletion.CASCADE, to='hackapp.user'),
        ),
    ]
